#!/usr/bin/perl -w

use ALL;

use UniLang::Agent::Agent;
use UniLang::Util::Message;

$UNIVERSAL::agent = UniLang::Agent::Agent->new
  (Name => "ALL",
   ReceiveHandler => \&Receive);
$UNIVERSAL::all = ALL->new();

sub Receive {
  my %args = @_;
  $UNIVERSAL::all->ProcessMessage
    (Message => $args{Message});
}

$UNIVERSAL::all->Execute();
